[tool.poetry]
name = "langchain-kr"
version = "0.1.0"
description = "langchain tutorial translated in Korean"
authors = ["teddy <teddylee777@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.1.13"
langchain-openai = "^0.1.1"
openai = "^1.14.3"
streamlit = "^1.32.2"
langchain-anthropic = "^0.1.4"
redis = "^5.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
