[tool.poetry]
name = "langchain-kr"
version = "0.1.0"
description = "langchain tutorial translated in Korean"
authors = ["teddy <teddylee777@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
langchain = "^0.1.13"
langchain-openai = "^0.1.1"
openai = "^1.14.3"
streamlit = "^1.32.2"
langchain-anthropic = "^0.1.4"
redis = "^5.0.3"
jupyter = "^1.0.0"
notebook = "^7.1.2"
matplotlib = "^3.8.4"
lark = "^1.1.9"
langchain-text-splitters = "^0.0.1"
langchain-community = "^0.0.31"
pymupdf = "^1.24.1"
chromadb = "^0.4.24"
faiss-cpu = "^1.8.0"
python-dotenv = "^1.0.1"
pypdf = "^4.2.0"
langgraph = "^0.0.32"
tiktoken = "^0.6.0"
langchainhub = "^0.1.15"
arxiv = "^2.1.0"
huggingface-hub = "^0.22.2"
rank-bm25 = "^0.2.2"
deepl = "^1.17.0"
langchain-elasticsearch = "^0.1.3"
ragas = "^0.1.7"
langchain-upstage = "^0.1.5"
langchain-chroma = "^0.1.1"
langchain-cohere = "^0.1.5"
kiwipiepy = "^0.17.1"
konlpy = "^0.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
